### ISSUE TITLE
Export Config: Simplify group styling

### ISSUE THREAD

**Issue by adamfranco** [middlebury/coursecatalog#4]
The current styling uses alternating colors for each group and a very heavy font, making the UI kind of heavy and a bit hard to scan/focus.
![screen shot 2018-02-06 at 4 23 40 pm](https://user-images.githubusercontent.com/25242/35884953-4eb57334-0b5a-11e8-91c8-77ab9d1ecb3a.png)

- [x] Use a single background color for groups.
- [x] Use a lighter or smaller font styling for the titles to make it easier to scan the list and find a particular department.
- [ ] (Maybe) Shift the insert links to the right (either a little or fully) to reduce visual clutter when scanning.

**Comment by cg923** [comment]
I have changed this so that the Delete Group and Add Group Below buttons are only visible when a group is expanded.  I originally left them visible all the time to save a button click to get to them, but I agree they add much visual clutter.

Here is a working example:
<img width="706" alt="screen shot 2018-02-06 at 2 28 18 pm" src="https://user-images.githubusercontent.com/28875167/35887727-0e2379f2-0b4a-11e8-9a12-9d03ad92c24c.png">

@adamfranco Do you think this solves the issue?

**Comment by adamfranco** [comment]
Yeah, that looks good! Way easier to scan. 👍
